name: repo release synchronize

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.MIN_GITHUB_TOKEN_SYNC }}
      gitcode_token: ${{ secrets.GITCODE_TOKEN_SYNC }}
      git_user: tzw-my
      git_email: tzw@x-cmd.com
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            . ./src/gh2gc
            ___x_cmd_repo_rm ${github_token} ${gitcode_token}