name: x pkg build

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.GITHUB_TOKEN_SYNC }}
      gitcode_token: ${{ secrets.GITCODE_TOKEN_SYNC }}
      git_user: tzw-my
      git_email: tzw@x-cmd.com
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            ls
            . ./src/gh2gc
            test ${github_token} ${gitcode_token}